services:
  selenium-chrome:
    build:
      context: ./navegador
    container_name: selenium-chrome
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "7900:7900"
    volumes:
      - chrome-profile:/home/seluser/chrome-profile
    restart: unless-stopped

  robo:
    build: .
    container_name: robo
    depends_on:
      - selenium-chrome
    environment:
      - SELENIUM_URL=http://selenium-chrome:4444/wd/hub
    volumes:
      - logs:/app/logs   # ðŸ”¹ persistÃªncia de logs
    restart: "no"

volumes:
  chrome-profile:
  logs:
